def Main():
    """This is the main program function"""

    def build_story(adj, name, nouns, noun, emotion):
        """A function to build a story and append to a list"""
        if adj == "Calm" or adj == 'calm':
                story_template = f"""On a {adj} morning, {name} felt 
            {emotion} as they went to the {nouns} to seek guidance. 
            As they prayed, a gentle light surrounded them, and they felt the presence of God. “You are never alone,” God said. 
            Suddenly, {noun} appeared, reminding {name} of the beauty in life. 
            With renewed faith, {name} left feeling {adj} and ready to face the world."""
        else:
            story_template = f"""On a {adj} day, {name} felt {emotion} as they prepared for the big match. 
            The stadium was filled with {nouns}, all cheering for their team. 
            As the {noun} began, {name} made an incredible play and scored a {adj} goal! 
            Everyone erupted in {nouns}, and {name} knew this was a moment to remember."""

        # Append/push to the story generated to empty list 
        user_madlibs_words.append(story_template)
        return user_madlibs_words

    # Set the variables
    game_active = False
    words_max_build = 2
    words_build = 0
    user_madlibs_words = []
    print("Welcome to Mad Libs Center...")
    print(f"Max story_generated: {words_max_build}")

    while not game_active and words_max_build > 0:
        adj = input("Adjective: ")
        name = input("Mascline Name: ")
        noun = input("Noun: ")
        nouns = input("Nouns: ")
        emotion = input("Emotiion: ")

        # Decrease the words built 
        words_max_build -= 1

        # increment the words_built
        words_build += 1

        # Function to build the story
        build_story(adj, name, noun, nouns, emotion)
        
        # Ask if user wants to continue building the madlibs or not
        ques = input("Do you want to continue (yes or no)?: ")
        if ques == "no" or ques == 'No':
            break
    
    # Display the Madlibs words generated along with the count
    print(f"\nYour words build: {words_build}")
    print("All stories generated by user for Madlibs: ")
    for story in user_madlibs_words:
        print(story)


# To excute only the current python file
if __name__ == '__main__':
    Main()
